spring:
    application:
        name: zuulproxyservice

zuul:
    host:
        connect-timeout-millis: 20000
        socket-timeout-millis: 20000
    routes:
        signin:
            url: http://authservice-service:8081/auth/signin
            sensitiveHeaders:
        signup:
            url: http://userservice-service:8087/user
            sensitiveHeaders:
        tweet:
            url: http://tweetservice-service:8082/tweet
            sensitiveHeaders:
        trend:
            url: http://tweetservice-service:8082/trend
            sensitiveHeaders:
        like:
            url: http://tweetservice-service:8082/like
            sensitiveHeaders:
        profile:
            url: http://profileservice-service:8084/profile
            sensitiveHeaders:
        following:
            url: http://followingservice-service:8083/following
            sensitiveHeaders:
        search:
            url: http://searchservice-service:8088/search
            sensitiveHeaders:
        moderatoruser:
            url: http://moderatorservice-service:8086/user
            sensitiveHeaders:
        moderatorrole:
            url: http://moderatorservice-service:8086/role
            sensitiveHeaders:
        adminuser:
            url: http://adminservice-service:8085/user
            sensitiveHeaders:
        adminrole:
            url: http://adminservice-service:8085/role
            sensitiveHeaders:

server:
    port: 8080
