spring:
    application:
        name: zuulproxyservice

zuul:
    host:
        connect-timeout-millis: 20000
        socket-timeout-millis: 20000
    routes:
        signin:
            url: http://localhost:8081/auth/signin
            sensitiveHeaders:
        signup:
            url: http://userservice-service:8087/user
            sensitiveHeaders:
        tweet:
            url: http://localhost:8082/tweet
            sensitiveHeaders:
        trend:
            url: http://tweetservice-service:8082/trend
            sensitiveHeaders:
        like:
            url: http://tweetservice-service:8082/like
            sensitiveHeaders:

server:
    port: 8080
