apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuulproxyservice-deployment
  labels:
    app: zuulproxyservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zuulproxyservice
  template:
    metadata:
      labels:
        app: zuulproxyservice
    spec:
      containers:
        - name: zuulproxyservice
          imagePullPolicy: Always
          image: imadelfetouh99/zuulproxyservice:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 256Mi
              cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: zuulproxyservice-service
spec:
  selector:
    app: zuulproxyservice
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080